# Auto-invoked by Resources.cmake to embed a binary file as a C++ byte array.
#
# Usage:
#   cmake -DINPUT=<path> -DOUTPUT=<path.cpp> -DVAR_NAME=<identifier> -P EmbedResource.cmake

cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED VAR_NAME)
    message(FATAL_ERROR "EmbedResource.cmake: INPUT, OUTPUT, and VAR_NAME must be defined.")
endif()

file(READ "${INPUT}" hex_content HEX)
string(LENGTH "${hex_content}" hex_len)

# Build the byte array body 16 bytes (32 hex chars) per line.
set(byte_lines "")
set(i 0)
while(i LESS ${hex_len})
    math(EXPR remaining "${hex_len} - ${i}")
    if(remaining GREATER 32)
        set(chunk_len 32)
    else()
        set(chunk_len ${remaining})
    endif()
    string(SUBSTRING "${hex_content}" ${i} ${chunk_len} chunk)
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " chunk_fmt "${chunk}")
    string(APPEND byte_lines "        ${chunk_fmt}\n")
    math(EXPR i "${i} + 32")
endwhile()

file(WRITE  "${OUTPUT}" "// Auto-generated by EmbedResource.cmake -- do not edit.\n")
file(APPEND "${OUTPUT}" "#include \"Fusion/Misc/CoreTypes.h\"\n\n")
file(APPEND "${OUTPUT}" "namespace Fusion::Resources::Embedded\n{\n\n")
file(APPEND "${OUTPUT}" "    static const Fusion::u8 Data_${VAR_NAME}[] =\n    {\n")
file(APPEND "${OUTPUT}" "${byte_lines}")
file(APPEND "${OUTPUT}" "    };\n\n")
file(APPEND "${OUTPUT}" "    const Fusion::u8* Res_${VAR_NAME}()      { return Data_${VAR_NAME}; }\n")
file(APPEND "${OUTPUT}" "    Fusion::SizeT     Res_${VAR_NAME}_Size() { return sizeof(Data_${VAR_NAME}); }\n\n")
file(APPEND "${OUTPUT}" "} // namespace Fusion::Resources::Embedded\n")
